// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGzOetdqg0yYatDFhaJO6uqRiKKcyzhHc',
    appId: '1:882930210875:web:13a47402546b833a6ba41e',
    messagingSenderId: '882930210875',
    projectId: 'raspadinhadogol',
    authDomain: 'raspadinhadogol.firebaseapp.com',
    storageBucket: 'raspadinhadogol.firebasestorage.app',
    measurementId: 'G-S332DVYP0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy1_1CoGv8VFMRC-36n-9kc3bYjIRFZoE',
    appId: '1:882930210875:android:94cb4eb454bd2fb36ba41e',
    messagingSenderId: '882930210875',
    projectId: 'raspadinhadogol',
    storageBucket: 'raspadinhadogol.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHrCDntmxqUY3XJdv3OeFssdW4kfS8l0',
    appId: '1:882930210875:ios:899ea05f26611ab26ba41e',
    messagingSenderId: '882930210875',
    projectId: 'raspadinhadogol',
    storageBucket: 'raspadinhadogol.firebasestorage.app',
    androidClientId: '882930210875-69is9s7i1i595q031ro915b9f1674b6o.apps.googleusercontent.com',
    iosClientId: '882930210875-29qhg8smsu6c9mabns686ca575thhfn1.apps.googleusercontent.com',
    iosBundleId: 'br.com.digitoinovacao.raspadinhaDoGol',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHrCDntmxqUY3XJdv3OeFssdW4kfS8l0',
    appId: '1:882930210875:ios:899ea05f26611ab26ba41e',
    messagingSenderId: '882930210875',
    projectId: 'raspadinhadogol',
    storageBucket: 'raspadinhadogol.firebasestorage.app',
    androidClientId: '882930210875-69is9s7i1i595q031ro915b9f1674b6o.apps.googleusercontent.com',
    iosClientId: '882930210875-29qhg8smsu6c9mabns686ca575thhfn1.apps.googleusercontent.com',
    iosBundleId: 'br.com.digitoinovacao.raspadinhaDoGol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGzOetdqg0yYatDFhaJO6uqRiKKcyzhHc',
    appId: '1:882930210875:web:fe7eafcc19e1d48b6ba41e',
    messagingSenderId: '882930210875',
    projectId: 'raspadinhadogol',
    authDomain: 'raspadinhadogol.firebaseapp.com',
    storageBucket: 'raspadinhadogol.firebasestorage.app',
    measurementId: 'G-083SLCYH1E',
  );
}
